---
# tasks file for apigee-opdk-setup-license
- name: Copy license file
  copy:
    src: "{{ opdk_license_source_file_name }}"
    dest: "{{ opdk_license_target_file_path }}"
    mode: 0644
    force: yes
